#!/usr/bin/env python3
"""kb-sync.py — regenerate a knowledge vault's navigation (MOC index files + INDEX.md) and its
two memory tiers (always-loaded MEMORY.md + the CLAUDE.md LIVE sync blocks) from shard frontmatter.

Idempotent. The shards are the source of truth (Karpathy layer 2); this keeps the navigation +
MemGPT-style core tier in sync. See ../research/agent-memory-landscape.md.

CONFIG (env vars, all optional — sensible defaults):
  KB_ROOT       project workspace root that holds CLAUDE.md + the vault   (default: two dirs up from this file)
  KB_VAULT      the vault dir                                             (default: $KB_ROOT/_knowledge)
  KB_MEMORY_DIR Claude Code project-memory dir (tier-1 auto-load)         (default: derived from KB_ROOT)
  KB_PROJECT    project name used in titles                               (default: basename of KB_ROOT)
  KB_TODAY      date stamp                                                (default: today via env or 'unset')

Copy this into a project's _meta/ (or tooling/) and run:  python3 kb-sync.py
"""
import glob, os, re
from collections import defaultdict

ROOT = os.environ.get("KB_ROOT") or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VAULT = os.environ.get("KB_VAULT") or os.path.join(ROOT, "_knowledge")
PROJECT = os.environ.get("KB_PROJECT") or os.path.basename(ROOT.rstrip("/"))
# Claude Code encodes a project dir by replacing os.sep with '-' and prefixing '-'.
_derived_mem = os.path.expanduser("~/.claude/projects/" + ROOT.replace("/", "-") + "/memory")
MEMORY_DIR = os.environ.get("KB_MEMORY_DIR") or _derived_mem
TODAY = os.environ.get("KB_TODAY", "unset")
GEN = "<!-- generated by kb-sync.py — do not hand-edit; edit shards then re-run -->"

# Order areas however your project likes; unknown areas sort after these.
AREAS = (os.environ.get("KB_AREAS") or "backend,frontend,mobile,infra,cross").split(",")
COLLECTIONS = ["gotchas", "decisions", "security", "tasks", "repos"]

def parse(path):
    txt = open(path, errors="ignore").read()
    fm = {}
    m = re.match(r'^---\n(.*?)\n---', txt, re.S)
    if m:
        for ln in m.group(1).splitlines():
            mm = re.match(r'^(\w+):\s*(.*)$', ln)
            if mm: fm[mm.group(1)] = mm.group(2).strip()
    return fm

def collect(subdir):
    out = []
    for f in sorted(glob.glob(os.path.join(VAULT, subdir, "*.md"))):
        fm = parse(f)
        if fm.get("name"): fm["_file"] = f; out.append(fm)
    return out

def line(fm):
    t = fm.get("title", fm["name"]).strip().strip('"')
    flag = " ⚠️" if fm.get("volatility") == "decays-with-code" else ""
    return f"- [[{fm['name']}]] — {t}{flag}"

def write(path, body):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w").write(body.rstrip() + "\n")
    print(f"  ✓ {os.path.relpath(path, ROOT)}")

def is_live(i, live_by):
    return i.get("volatility") == "decays-with-code" if live_by == "volatility" else i.get("status") == "active"

def moc(title, subdir, intro, group_by_area=False, split_status=False,
        live_by="status", live_label="LIVE", rest_label="Durable / resolved"):
    items = collect(subdir)
    body = [f"---\ntype: moc\ntitle: {title}\nupdated: {TODAY}\n---\n", GEN, f"\n# {title}\n", intro, ""]
    if split_status:
        live = [i for i in items if is_live(i, live_by)]; rest = [i for i in items if not is_live(i, live_by)]
        body += [f"## 🔴 {live_label} ({len(live)})\n"] + ([line(i) for i in live] or ["_none_"])
        body += [f"\n## {rest_label} ({len(rest)})\n"] + ([line(i) for i in rest] or ["_none_"])
    elif group_by_area:
        by = defaultdict(list)
        for i in items: by[i.get("area", "other")].append(i)
        for a in [x for x in AREAS if x in by] + [x for x in by if x not in AREAS]:
            body += [f"## {a} ({len(by[a])})\n"] + [line(i) for i in by[a]] + [""]
    else:
        body += [line(i) for i in items]
    body.append(f"\n*{len(items)} shards. Generated — edit shards, then `python3 kb-sync.py`.*")
    write(os.path.join(VAULT, subdir + ".md"), "\n".join(body))
    return items

def index(counts, has_arch):
    refs = sorted(os.path.basename(f) for f in glob.glob(os.path.join(VAULT, "reference", "*.md")))
    body = [f"---\ntype: index\ntitle: {PROJECT} knowledge — map of content\nupdated: {TODAY}\n---\n", GEN,
            f"\n# {PROJECT} knowledge — INDEX\n",
            "Read this first. Open only the pages you need. New here? Read [[README]] for schema + discipline.\n",
            "## Volatility (read before trusting a shard)",
            "- **durable** — timeless. Trust it.",
            "- **decays-with-code** ⚠️ — true only as of `updated:`; re-verify against the code first.",
            "- **one-shot** — closed/resolved record.\n",
            "## Collections", "| MOC | Shards | What's in it |", "|---|---|---|",
            f"| [[repos]] | {counts['repos']} | one page per repo/component |",
            (f"| [[architecture]] | 1 | system model |" if has_arch else ""),
            f"| [[gotchas]] | {counts['gotchas']} | non-obvious traps |",
            f"| [[decisions]] | {counts['decisions']} | ADR-style — why |",
            f"| [[security]] | {counts['security']} | rules + open findings |",
            f"| [[tasks]] | {counts['tasks']} | remaining work |\n",
            "## Reference (raw-source backbone — Karpathy layer 1)"]
    body += [f"- `reference/{r}`" for r in refs] or ["- _(none yet)_"]
    body += ["\n## The two tiers (MemGPT-style)",
             f"- **Core (always-loaded):** `{MEMORY_DIR}/MEMORY.md` — tiny, pointers + LIVE state.",
             "- **Archival (on-demand):** this vault — browse this INDEX, open the few pages you need.\n",
             f"*{sum(counts.values())} shards total. Generated — edit shards, then `python3 kb-sync.py`.*"]
    write(os.path.join(VAULT, "INDEX.md"), "\n".join(x for x in body if x != ""))

def memory(sec, tsk):
    os.makedirs(MEMORY_DIR, exist_ok=True)
    live_sec = [i for i in sec if i.get("volatility") == "decays-with-code"]
    live_tsk = [i for i in tsk if i.get("status") == "active"]
    notes = sorted(os.path.basename(f) for f in glob.glob(os.path.join(MEMORY_DIR, "*.md")) if os.path.basename(f) != "MEMORY.md")
    def t(i): return i.get("title", i["name"]).strip().strip('"')
    body = [f"# {PROJECT} — always-loaded memory (tier-1 core)\n", GEN,
            f"\nMemGPT-style **core** tier: tiny, pointers only. Full wiki (archival) at `{VAULT}` —",
            "read its `INDEX.md` first, open only the pages you need.\n",
            "## First action every session",
            f"`cat {VAULT}/INDEX.md` — then open the shards you need.\n",
            "## Saved notes"] + ([f"- [{f[:-3]}]({f})" for f in notes] or ["- _(none yet)_"])
    body += [f"\n## 🔴 LIVE — open security findings ({len(live_sec)}) — verify before acting"] + \
            ([f"- [[{i['name']}]] — {t(i)}" for i in live_sec] or ["- _none open_"])
    body += [f"\n## 🟠 LIVE — open work ({len(live_tsk)})"] + \
            ([f"- [[{i['name']}]] — {t(i)}" for i in live_tsk] or ["- _none open_"])
    body.append("\n*LIVE sections generated from vault frontmatter. Re-run `kb-sync.py` after editing shards. These decay.*")
    write(os.path.join(MEMORY_DIR, "MEMORY.md"), "\n".join(body))

def sync_claude_md(sec, tsk):
    path = os.path.join(ROOT, "CLAUDE.md")
    if not os.path.exists(path): return
    txt = open(path, errors="ignore").read()
    def t(i): return i.get("title", i["name"]).strip().strip('"')
    blocks = {
        "live-security": "\n".join(f"- [[{i['name']}]] — {t(i)}" for i in sec if i.get("volatility") == "decays-with-code") or "_none open_",
        "open-work": "\n".join(f"- [[{i['name']}]] — {t(i)}" for i in tsk if i.get("status") == "active") or "_none open_",
    }
    hit = 0
    for name, content in blocks.items():
        b, e = f"<!-- BEGIN:sync:{name} -->", f"<!-- END:sync:{name} -->"
        pat = re.compile(re.escape(b) + r".*?" + re.escape(e), re.S)
        if pat.search(txt): txt = pat.sub(f"{b}\n{content}\n{e}", txt); hit += 1
    if hit: open(path, "w").write(txt); print(f"  ✓ CLAUDE.md ({hit} LIVE blocks synced)")

if __name__ == "__main__":
    print(f"Regenerating {PROJECT} KB navigation + core tier…  (vault: {VAULT})")
    g = moc("Gotchas", "gotchas", "Non-obvious traps. Atomic; append new ones.", group_by_area=True)
    d = moc("Decisions", "decisions", "ADR-style — why things are the way they are.")
    s = moc("Security", "security", "Recurring security rules + open findings.", split_status=True,
            live_by="volatility", live_label="Open findings — verify/fix (decays-with-code)", rest_label="Durable rules")
    t = moc("Tasks", "tasks", "Remaining work. LIVE = still open.", split_status=True,
            live_label="Open work (status: active)", rest_label="Done / historical")
    r = moc("Repos", "repos", "One page per repo/component. See [[architecture]] for how they fit together.")
    counts = {c: len(x) for c, x in zip(COLLECTIONS, [g, d, s, t, r])}
    index(counts, os.path.exists(os.path.join(VAULT, "architecture.md")))
    memory(s, t)
    sync_claude_md(s, t)
    print(f"Done. {sum(counts.values())} shards indexed: {counts}")
